### ISSUE TITLE
New Textile Preview No Longer Support Strikeout?

### ISSUE THREAD

**Issue by timknight** [textmate/textile.tmbundle#2]
After applying the new 1616 Textmate build the textile preview no longer uses the previous textile preview page, but instead a Textmate branded preview window. This new preview window is not processing strikeouts as it previously was. So text like "-This is great-" renders with the dashes still in place.

**Comment by infininight** [comment]
This is working for me, try reverting to default bundles to see if it is a local issue:

http://wiki.macromates.com/Troubleshooting/RevertToDefaultBundles

**Comment by timknight** [comment]
After uninstalling everything and limiting TextMate only down to Textile I came across some addition details of the bug.

The strikethrough does not process if it begins a line. For example:

-This- doesn't work.

This -does- work.

This is similarly as valid within a list.
- -This- doesn't work.
- This -does- work.

**Comment by infininight** [comment]
All these cases are working fine here, double check for any local modifications and if you can try it under another user to see it is local to your user.

**Comment by timknight** [comment]
I've removed all local modifications - removing all bundles aside that which aren't native in the applications (though have disabled all but Textile during my testing). The issue I stated above regarding striking through the first item has been duplicated on three machines each running 1.5.10 (1616) or 1623.

**Comment by infininight** [comment]
Are you able to come discuss this with me on IRC? (freenode.net ##textmate I am Infininight there too)

**Comment by timknight** [comment]
No problem, I'll be on IRC tomorrow and I'll look for you. I really appreciate you trying to help me figure this out.

**Comment by infininight** [comment]
Turns out it was an outdated gem causing the errors, closing.
